import type { Metadata } from "next";
import "../globals.css";
import { kanit } from "../fonts";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} antialiased`}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
